### ISSUE TITLE
Fail to record video

### ISSUE THREAD

**Issue by yxdydgithub** [vwxyzjn/cleanrl#384]
command:
`python3 cleanrl/rpo_continuous_action.py --env-id Humanoid-v4 --track --wandb-project-name rpotest --capture-video`
Video size is so small except first. 
![Screenshot from 2023-05-08 20-11-11](https://user-images.githubusercontent.com/10349365/236820766-bcd99cec-6958-4909-9610-a1207ca92941.png)

**Comment by itstyren** [comment]
A similar issue has been brought to the attention of the Gymnasium. A temporary solution has been suggested and can be found [here](https://github.com/Farama-Foundation/Gymnasium/issues/312#issuecomment-1420848277).

**Comment by vwxyzjn** [comment]
Should be fixed in the master now.

**Comment by herbat** [comment]
I'm still having this issue on master. Fix mentioned  [here](https://github.com/Farama-Foundation/Gymnasium/issues/312#issuecomment-1420848277) worked.
